# 运行模式
# pre_run:      指引获取uin、skey，以及如何获取角色信息
# normal:       走正常流程，执行签到、完成任务、领奖、兑换等流程
run_mode = "pre_run"

# 日志等级, 级别从低到高依次为 "debug", "info", "warning", "error", "critical"
log_level = "info"

# 是否检查更新
check_update_on_start = true
readme_page = "https://github.com/fzls/djc_helper/blob/master/README.MD"
changelog_page = "https://github.com/fzls/djc_helper/blob/master/CHANGELOG.MD"

# 腾讯系网页登录通用账号凭据与token
[account_info]
uin = "o123456789"
skey = "@a1b2c3d4e"

# 兑换道具所需的区服和角色信息，目前限定为dnf，之后可能支持更多
[exchange_role_info]
iZone = "11"  # 浙江一区，其他区服id可查阅reference_data/dnf_server_list.js
lRoleId = "DNF角色ID"
rolename = "DNF角色名"

# 完成《礼包达人》任务所需的手游的区服和角色信息，目前限定为剑网3:指尖江湖，之后可能支持更多
[mobile_game_role_info]
# 手游名称，目前支持下面几种，后续有空可能会添加其他手游
# none： 无，则不启用完成礼包达人任务
# jx3：  剑网3：指尖江湖
game_name = "jx3"
area = 2  # QQ，其他渠道的id可查阅reference_data/jx3_server_list.js的 STD_CHANNEL_DATA中对应渠道的v
platid = 1  # 安卓，其他系统的id可查阅reference_data/jx3_server_list.js的 STD_SYSTEM_DATA中对应系统的v
partition = 20001  # 手Q1区，其他区服的id可查阅reference_data/jx3_server_list.js的 STD_DATA中对应服务器的v
roleid = "指尖江湖角色ID"
rolename ="指尖江湖玩家名"

# 兑换道具信息，其他奖励信息可查阅reference_data/dnf_exchange_list.json
[[exchange_items]]
# 兑换两次调整箱
iGoodsId = "753"
sGoodsName = "装备品级调整箱（5个）"
count = 2

[[exchange_items]]
# 兑换一次疲劳药
iGoodsId = "755"
sGoodsName = "魔界抗疲劳秘药（10点）"
count = 1