# 本配置文件仅展示普通用户需要的一些配置，完整列表请查看config.toml.example，有需求可自行将对应配置项添加到本配置文件中

# 所有账号共用的配置
[common]
# 心悦相关配置
[common.xinyue]
# 在每日几点后才尝试提交心悦的成就点任务，避免在没有上游戏时执行心悦成就点任务，导致高成就点的任务没法完成，只能完成低成就点的
submit_task_after = 0

# 固定队相关配置。用于本地三个号来组成一个固定队伍，完成心悦任务。
[[common.fixed_teams]]
# 是否启用该固定队
enable = false
# 固定队伍id，仅用于本地区分用
id = "1"
# 固定队成员，必须是三个，则必须都配置在本地的账号列表中了，否则将报错，不生效
members = ["小队第一个账号的QQ号", "小队第二个账号的QQ号", "小队第三个账号的QQ号"]

# 第二个固定队，更多的固定队则以此类推
[[common.fixed_teams]]
# 是否启用该固定队
enable = false
# 固定队伍id，仅用于本地区分用
id = "2"
# 固定队成员，必须是三个，否则将报错
members = ["小队第一个账号的QQ号", "小队第二个账号的QQ号", "小队第三个账号的QQ号"]

# ---------------------------第1个账号相关配置开始-----------------------------
[[account_configs]]
# 是否启用该账号
enable = true

# 账号名称，仅用于区分不同账号
name = "默认账号"

# 运行模式
# pre_run:      指引获取uin、skey，以及指引前往道聚城绑定对应角色信息
# normal:       走正常流程，执行签到、完成任务、领奖、兑换等流程
run_mode = "pre_run"

# 登录模式
# by_hand：      手动登录，在skey无效的情况下会弹出活动界面，自行登录后将cookie中uin和skey提取到下面的配置处
# qr_login：     二维码登录，每次运行时若本地缓存的.skey文件中存储的skey过期了，则弹出登录页面，扫描二维码后将自动更新skey，进行后续操作
# auto_login：   自动登录，每次运行若本地缓存的.skey文件中存储的skey过期了，根据填写的账密信息，自动登录来获取uin和skey，无需手动操作
login_mode = "qr_login"

# 各功能开关
[account_configs.function_switches]
# 是否领取每月黑钻等级礼包
get_heizuan_gift = true
# 是否领取心悦国庆活动
get_xinyue_guoqing = true
# 是否领取wegame国庆活动
get_wegame_guoqing = true

# 腾讯系网页登录通用账号凭据与token
[account_configs.account_info]
# 手动登录需要设置的信息
uin = "o123456789"
skey = "@a1b2c3d4e"
# QQ空间业务群的p_skey，目前用于抽卡活动
qzone_p_skey = "666666eE2KLV6oYFGx2iYZ9b3UtQuwNitJiPGQ52b*w_"

# 自动登录需要设置的信息
account = "123456789"
password = "使用账号密码自动登录有风险_请审慎决定"

# 完成《礼包达人》任务所需的手游的名称信息
[account_configs.mobile_game_role_info]
# 手游名称: 无/任意手游/剑网3:指尖江湖/和平精英/王者荣耀/QQ飞车手游/天天酷跑/其他任意游戏，可参考djc_biz_list.json获取完整列表
game_name = "任意手游"

# 兑换道具信息，其他奖励信息可查阅reference_data/dnf_exchange_list.json
[[account_configs.exchange_items]]
# 兑换两次调整箱
iGoodsId = "753"
sGoodsName = "装备品级调整箱（5个）"
count = 2

[[account_configs.exchange_items]]
# 兑换一次疲劳药
iGoodsId = "755"
sGoodsName = "魔界抗疲劳秘药（10点）"
count = 1

# 心悦相关操作信息，其他心悦相关信息可查阅reference_data/心悦活动备注.txt
# note: 周期礼包目前在代码中根据心悦级别和白名单信息来自动判定该领取哪一类，无需手动操作，若发现有问题，也可以手动取消注释下列内容来手动启用对应礼包
## ++++++++++周期礼包++++++++++++
#[[account_configs.xinyue_operations]]
## 尝试领取每周礼包（特邀会员）
#iFlowId = "513581"
#sFlowName = "Y600周礼包_特邀会员"
#count = 1
#
#[[account_configs.xinyue_operations]]
## 尝试领取每月礼包（特邀会员）
#iFlowId = "673270"
#sFlowName = "月礼包_特邀会员_20200610后使用"
#count = 1
#
#[[account_configs.xinyue_operations]]
## 尝试领取每周礼包（心悦会员）
#iFlowId = "513573"
#sFlowName = "Y600周礼包"
#count = 1
#
#[[account_configs.xinyue_operations]]
## 尝试领取每月礼包（心悦会员）
#iFlowId = "673269"
#sFlowName = "月礼包_20200610后使用"
#count = 1
#
#[[account_configs.xinyue_operations]]
## 尝试领取周礼包_白名单用户（心悦会员）
#iFlowId = "673262"
#sFlowName = "周礼包_白名单用户"
#count = 1
#
#[[account_configs.xinyue_operations]]
## 尝试领取月礼包_白名单用户（心悦会员）
#iFlowId = "673264"
#sFlowName = "月礼包_白名单用户"
#count = 1
#
#[[account_configs.xinyue_operations]]
## 尝试领取每月累计宝箱（月领取周期礼包达到5个可领取）
#iFlowId = "513585"
#sFlowName = "累计宝箱"
#count = 1

# ++++++++++每日任务++++++++++++
# 下列默认尝试按照成就点数从高到低完成任务，可根据自己的游戏习惯进行调整
# 建议设置为在每天比较迟的时间自动运行，这样可以尽可能确保运行的时候任务的条件已达成
[[account_configs.xinyue_operations]]
iFlowId = "512408"
sFlowName = "每月赠送双倍积分卡（仅心悦会员）"
count = 1

# ------------双倍（仅尝试最高级别的，不然比较浪费）----------------
[[account_configs.xinyue_operations]]
iFlowId = "512432"
sFlowName = "充值DNF3000点券_双倍（成就点=6）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512435"
sFlowName = "游戏内消耗疲劳值120_双倍（成就点=6）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512437"
sFlowName = "游戏内在线时长40_双倍（成就点=6）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512441"
sFlowName = "游戏内PK3次_双倍（成就点=6）"
count = 1

# -----------普通------------------
[[account_configs.xinyue_operations]]
iFlowId = "512396"
sFlowName = "充值DNF3000点券（成就点=3）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512398"
sFlowName = "游戏内在线时长40（成就点=3）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512400"
sFlowName = "游戏内消耗疲劳值120（成就点=3）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512402"
sFlowName = "游戏内PK3次（成就点=3）"
count = 1

# -----------免做（仅尝试最高级别的，不然比较浪费）------------------
[[account_configs.xinyue_operations]]
iFlowId = "512490"
sFlowName = "领取每周免做卡"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512415"
sFlowName = "充值DNF3000点券_免做（成就点=3）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512418"
sFlowName = "游戏内消耗疲劳值120_免做（成就点=3）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512421"
sFlowName = "游戏内在线时长40_免做（成就点=3）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512424"
sFlowName = "游戏内PK3次_免做（成就点=3）"
count = 1

# -----------如果还没做完三个，尝试一些普通任务，但是免做任务和双倍不尝试非3点的，避免浪费------------------
[[account_configs.xinyue_operations]]
iFlowId = "512395"
sFlowName = "充值DNF2000点券（成就点=2）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512397"
sFlowName = "游戏内在线时长30（成就点=2）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512399"
sFlowName = "游戏内消耗疲劳值50（成就点=2）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512401"
sFlowName = "游戏内PK2次（成就点=2）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512393"
sFlowName = "邮箱无未读邮件（成就点=2）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "578321"
sFlowName = "精英赛投票（成就点=未知）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512388"
sFlowName = "充值DNF1000点券（成就点=1）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512389"
sFlowName = "游戏内在线时长15（成就点=1）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512390"
sFlowName = "游戏内消耗疲劳值10（成就点=1）"
count = 1

[[account_configs.xinyue_operations]]
iFlowId = "512391"
sFlowName = "游戏内PK1次（成就点=1）"
count = 1

# ++++++++++组队++++++++++++
#[[account_configs.xinyue_operations]]
#iFlowId = "513512"
#sFlowName = "创建小队"
#count = 1

# ++++++++++兑换道具++++++++++++
# 下面是可供兑换的道具，默认不开启，可根据需要自行取消注释来启用自动兑换
#[[account_configs.xinyue_operations]]
#iFlowId = "512475"
#sFlowName = "抗疲劳秘药50点（95lv以上，1天1次）（1个）(需50点)(日限3)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512474"
#sFlowName = "时间引导石礼包 (10个)(需10点)(日限5)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512473"
#sFlowName = "复活币礼袋兑换(需8点)(日限10)"
#count = 1

#[[account_configs.xinyue_operations]]
#iFlowId = "512469"
#package_id = "702214"
#sFlowName = "装备品级调整箱(需8点)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512469"
#package_id = "702216"
#sFlowName = "超级远古精灵秘药（持续30分钟）(需10点)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512469"
#package_id = "702217"
#sFlowName = "神秘契约礼袋（适用1日）(需20点)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512469"
#package_id = "702218"
#sFlowName = "装备提升礼盒(需10点)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512469"
#package_id = "702220"
#sFlowName = "华丽徽章随机礼盒(需20点)"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512469"
#package_id = "702222"
#sFlowName = "升级券(Lv90-94)(需50点)(月限1)"
#count = 1

# 抽卡相关配置
[account_configs.ark_lottery]
# 尝试使用卡牌抽奖的次数
lottery_using_cards_count = 0

## 尝试领取礼包的次数：勇士归来礼包=25947，超低门槛=25948，人人可玩=25966，幸运礼包=25939
#[[account_configs.ark_lottery.take_awards]]
#name = "勇士归来礼包"
#ruleid = 25947
#count = 1
#
#[[account_configs.ark_lottery.take_awards]]
#name = "超低门槛"
#ruleid = 25948
#count = 1
#
#[[account_configs.ark_lottery.take_awards]]
#name = "人人可玩"
#ruleid = 25966
#count = 1
#
#[[account_configs.ark_lottery.take_awards]]
#name = "幸运礼包"
#ruleid = 25939
#count = 1

# ---------------------------第1个账号相关配置结束-----------------------------


## 取消下面的注释，即可得到第二个账户的配置，与第1个账户的配置一致。如果要添加更多账户，则再额外复制一份从（相关配置开始）到（相关配置结尾）内的内容到文件末尾
## 多账号的具体配置方式，可以查看使用文档
## ---------------------------第2个账号相关配置开始-----------------------------
#[[account_configs]]
## 是否启用该账号
#enable = true
#
## 账号名称，仅用于区分不同账号
#name = "大号"
#
## 运行模式
## pre_run:      指引获取uin、skey，以及指引前往道聚城绑定对应角色信息
## normal:       走正常流程，执行签到、完成任务、领奖、兑换等流程
#run_mode = "pre_run"
#
## 登录模式
## by_hand：      手动登录，在skey无效的情况下会弹出活动界面，自行登录后将cookie中uin和skey提取到下面的配置处
## qr_login：     二维码登录，每次运行时若本地缓存的.skey文件中存储的skey过期了，则弹出登录页面，扫描二维码后将自动更新skey，进行后续操作
## auto_login：   自动登录，每次运行若本地缓存的.skey文件中存储的skey过期了，根据填写的账密信息，自动登录来获取uin和skey，无需手动操作
#login_mode = "qr_login"
#
## 各功能开关
#[account_configs.function_switches]
## 是否领取每月黑钻等级礼包
#get_heizuan_gift = true
## 是否领取心悦国庆活动
#get_xinyue_guoqing = true
## 是否领取wegame国庆活动
#get_wegame_guoqing = true
#
## 腾讯系网页登录通用账号凭据与token
#[account_configs.account_info]
## 手动登录需要设置的信息
#uin = "o123456789"
#skey = "@a1b2c3d4e"
## QQ空间业务群的p_skey，目前用于抽卡活动
#qzone_p_skey = "666666eE2KLV6oYFGx2iYZ9b3UtQuwNitJiPGQ52b*w_"
#
## 自动登录需要设置的信息
#account = "123456789"
#password = "使用账号密码自动登录有风险_请审慎决定"
#
## 完成《礼包达人》任务所需的手游的名称信息
#[account_configs.mobile_game_role_info]
## 手游名称: 无/任意手游/剑网3:指尖江湖/和平精英/王者荣耀/QQ飞车手游/天天酷跑/其他任意游戏，可参考djc_biz_list.json获取完整列表
#game_name = "任意手游"
#
## 兑换道具信息，其他奖励信息可查阅reference_data/dnf_exchange_list.json
#[[account_configs.exchange_items]]
## 兑换两次调整箱
#iGoodsId = "753"
#sGoodsName = "装备品级调整箱（5个）"
#count = 2
#
#[[account_configs.exchange_items]]
## 兑换一次疲劳药
#iGoodsId = "755"
#sGoodsName = "魔界抗疲劳秘药（10点）"
#count = 1
#
## 心悦相关操作信息，其他心悦相关信息可查阅reference_data/心悦活动备注.txt
## note: 周期礼包目前在代码中根据心悦级别和白名单信息来自动判定该领取哪一类，无需手动操作，若发现有问题，也可以手动取消注释下列内容来手动启用对应礼包
### ++++++++++周期礼包++++++++++++
##[[account_configs.xinyue_operations]]
### 尝试领取每周礼包（特邀会员）
##iFlowId = "513581"
##sFlowName = "Y600周礼包_特邀会员"
##count = 1
##
##[[account_configs.xinyue_operations]]
### 尝试领取每月礼包（特邀会员）
##iFlowId = "673270"
##sFlowName = "月礼包_特邀会员_20200610后使用"
##count = 1
##
##[[account_configs.xinyue_operations]]
### 尝试领取每周礼包（心悦会员）
##iFlowId = "513573"
##sFlowName = "Y600周礼包"
##count = 1
##
##[[account_configs.xinyue_operations]]
### 尝试领取每月礼包（心悦会员）
##iFlowId = "673269"
##sFlowName = "月礼包_20200610后使用"
##count = 1
##
##[[account_configs.xinyue_operations]]
### 尝试领取周礼包_白名单用户（心悦会员）
##iFlowId = "673262"
##sFlowName = "周礼包_白名单用户"
##count = 1
##
##[[account_configs.xinyue_operations]]
### 尝试领取月礼包_白名单用户（心悦会员）
##iFlowId = "673264"
##sFlowName = "月礼包_白名单用户"
##count = 1
##
##[[account_configs.xinyue_operations]]
### 尝试领取每月累计宝箱（月领取周期礼包达到5个可领取）
##iFlowId = "513585"
##sFlowName = "累计宝箱"
##count = 1
#
## ++++++++++每日任务++++++++++++
## 下列默认尝试按照成就点数从高到低完成任务，可根据自己的游戏习惯进行调整
## 建议设置为在每天比较迟的时间自动运行，这样可以尽可能确保运行的时候任务的条件已达成
#[[account_configs.xinyue_operations]]
#iFlowId = "512408"
#sFlowName = "每月赠送双倍积分卡（仅心悦会员）"
#count = 1
#
## ------------双倍（仅尝试最高级别的，不然比较浪费）----------------
#[[account_configs.xinyue_operations]]
#iFlowId = "512432"
#sFlowName = "充值DNF3000点券_双倍（成就点=6）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512435"
#sFlowName = "游戏内消耗疲劳值120_双倍（成就点=6）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512437"
#sFlowName = "游戏内在线时长40_双倍（成就点=6）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512441"
#sFlowName = "游戏内PK3次_双倍（成就点=6）"
#count = 1
#
## -----------普通------------------
#[[account_configs.xinyue_operations]]
#iFlowId = "512396"
#sFlowName = "充值DNF3000点券（成就点=3）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512398"
#sFlowName = "游戏内在线时长40（成就点=3）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512400"
#sFlowName = "游戏内消耗疲劳值120（成就点=3）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512402"
#sFlowName = "游戏内PK3次（成就点=3）"
#count = 1
#
## -----------免做（仅尝试最高级别的，不然比较浪费）------------------
#[[account_configs.xinyue_operations]]
#iFlowId = "512490"
#sFlowName = "领取每周免做卡"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512415"
#sFlowName = "充值DNF3000点券_免做（成就点=3）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512418"
#sFlowName = "游戏内消耗疲劳值120_免做（成就点=3）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512421"
#sFlowName = "游戏内在线时长40_免做（成就点=3）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512424"
#sFlowName = "游戏内PK3次_免做（成就点=3）"
#count = 1
#
## -----------如果还没做完三个，尝试一些普通任务，但是免做任务和双倍不尝试非3点的，避免浪费------------------
#[[account_configs.xinyue_operations]]
#iFlowId = "512395"
#sFlowName = "充值DNF2000点券（成就点=2）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512397"
#sFlowName = "游戏内在线时长30（成就点=2）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512399"
#sFlowName = "游戏内消耗疲劳值50（成就点=2）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512401"
#sFlowName = "游戏内PK2次（成就点=2）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512393"
#sFlowName = "邮箱无未读邮件（成就点=2）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "578321"
#sFlowName = "精英赛投票（成就点=未知）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512388"
#sFlowName = "充值DNF1000点券（成就点=1）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512389"
#sFlowName = "游戏内在线时长15（成就点=1）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512390"
#sFlowName = "游戏内消耗疲劳值10（成就点=1）"
#count = 1
#
#[[account_configs.xinyue_operations]]
#iFlowId = "512391"
#sFlowName = "游戏内PK1次（成就点=1）"
#count = 1
#
## ++++++++++组队++++++++++++
##[[account_configs.xinyue_operations]]
##iFlowId = "513512"
##sFlowName = "创建小队"
##count = 1
#
## ++++++++++兑换道具++++++++++++
## 下面是可供兑换的道具，默认不开启，可根据需要自行取消注释来启用自动兑换
##[[account_configs.xinyue_operations]]
##iFlowId = "512475"
##sFlowName = "抗疲劳秘药50点（95lv以上，1天1次）（1个）(需50点)(日限3)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512474"
##sFlowName = "时间引导石礼包 (10个)(需10点)(日限5)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512473"
##sFlowName = "复活币礼袋兑换(需8点)(日限10)"
##count = 1
#
##[[account_configs.xinyue_operations]]
##iFlowId = "512469"
##package_id = "702214"
##sFlowName = "装备品级调整箱(需8点)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512469"
##package_id = "702216"
##sFlowName = "超级远古精灵秘药（持续30分钟）(需10点)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512469"
##package_id = "702217"
##sFlowName = "神秘契约礼袋（适用1日）(需20点)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512469"
##package_id = "702218"
##sFlowName = "装备提升礼盒(需10点)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512469"
##package_id = "702220"
##sFlowName = "华丽徽章随机礼盒(需20点)"
##count = 1
##
##[[account_configs.xinyue_operations]]
##iFlowId = "512469"
##package_id = "702222"
##sFlowName = "升级券(Lv90-94)(需50点)(月限1)"
##count = 1
#
## 抽卡相关配置
#[account_configs.ark_lottery]
## 尝试使用卡牌抽奖的次数
#lottery_using_cards_count = 0
#
## 尝试领取礼包的次数：勇士归来礼包=25947，超低门槛=25948，人人可玩=25966，幸运礼包=25939
#[[account_configs.ark_lottery.take_awards]]
#name = "勇士归来礼包"
#ruleid = 25947
#count = 1
#
#[[account_configs.ark_lottery.take_awards]]
#name = "超低门槛"
#ruleid = 25948
#count = 1
#
#[[account_configs.ark_lottery.take_awards]]
#name = "人人可玩"
#ruleid = 25966
#count = 1
#
#[[account_configs.ark_lottery.take_awards]]
#name = "幸运礼包"
#ruleid = 25939
#count = 1
##
## ---------------------------第2个账号相关配置结束-----------------------------

