name: Package Exe

on: [ create, workflow_dispatch ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Requirements
        run: |
          _install_requirements.bat
      - name: Build
        run: |
          python _build.py
      - name: Package
        run: |
          python _package.py
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "DNF蚊子腿小助手.7z"
          path: ./releases/_github_action_artifact/DNF蚊子腿小助手.7z
